### ISSUE TITLE
I can't login my mc acc when im in cb

### ISSUE THREAD

**Issue by HoldMyVotka** [Offline-Cheatbreaker/Client#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. `windows 7`]
 - Game version [e.g. `1.8.9`]
 - Game build number [e.g. `038d0a3/master`]
 - Launcher version [e.g. `2.0.0 Beta 5`]
 - If on **Linux**, provide the output of `java -version` from Terminal

**Additional context**

**Comment by ShonP40** [comment]
Please provide all required information by editing your message and filling out the template.

**Comment by HoldMyVotka** [comment]
i am sorrry but I don't know the what to put at the other stuff

**Comment by ShonP40** [comment]
At least describe your issue
Like, what did you do and what error did you get, which MC account type did you try to use (Legacy, Mojang or Microsoft), etc...

**Comment by HoldMyVotka** [comment]
Mojang acc, the eror is: "An error occured when logging you in. Please try Regular Minecraft launcher

**Comment by ShonP40** [comment]
Are you typing in the correct details?
(Your Mojang Email and Password)

**Comment by HoldMyVotka** [comment]
Oh I puted my username ower email, ty

**Comment by ShonP40** [comment]
np
