### ISSUE TITLE
Error when trying to launch 1.7.10

### ISSUE THREAD

**Issue by leoghs** [Offline-Cheatbreaker/Client#10]
Describe the bug
When I try to launch 1.7.10 it errors and then gets stuck on "Launching..."
To Reproduce
Open Offline Cheatbreaker launcher
Select 1.7.10
Click "Launch 1.7.10"
Expected behavior
It launches normally and doesn't error
Screenshots
https://files.zylon.moe/sekret100/2021-02-22%2015-10-30.mp4
Please complete the following information:

    OS: Windows 10 20H2
    Game version 1.7.10
    Game build number no idea if i cant see it lol
    Launcher version Beta 8

**Comment by ShonP40** [comment]
Can you:
- Go into your Minecraft folder (`%appdata%\.minecraft`)
- Delete the `launcher_accounts.json` file
- Open the normal MC launcher and relog into your account(s)
- Try to launch CB 1.7 again

**Comment by leoghs** [comment]
Thank you!
