### ISSUE TITLE
Hello, I wanted to say that I can not log in to my premium account, maybe because I have mincrosoft but I don't know, please help me in this matter

### ISSUE THREAD

**Issue by hubertasus** [Offline-Cheatbreaker/Client#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: 
 - Game version: 
 - Game build number: 
 - Launcher version: 

**Additional context**

**Comment by ShonP40** [comment]
The issue was closed because the issue template was not filled out.

If the problem still occurs, create a new issue and fill out the template.
