### ISSUE TITLE
I try install Beta 8 version of CheatBreaker and it keeps installing the Beta 6 version, could you maybe help me by telling me what to do or tell me what the discord server is? Thanks.

### ISSUE THREAD

**Issue by rainswrld** [Offline-Cheatbreaker/Client#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: 
 - Game version: 
 - Game build number: 
 - Launcher version: 

**Additional context**

**Comment by ShonP40** [comment]
1. Download the latest installer from our website (https://offlinecheatbreaker.com)

2. The issue was closed because the issue template was not filled out.
If the problem still occurs, create a new issue and fill out the template.
