### ISSUE TITLE
Can't launch 1.8

### ISSUE THREAD

**Issue by WTRM3L0N** [Offline-Cheatbreaker/Client#13]
**Describe the bug**

when i click launch 1.8.9 it opens minecraft for a split section then closes instantly 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: 
 - Game version: 
 - Game build number: 
 - Launcher version: 

**Additional context**

**Comment by ShonP40** [comment]
The issue was closed because the issue template was not filled out.
If the problem still occurs, create a new issue and fill out the template.
