### ISSUE TITLE
Cant launch 1.8.9

### ISSUE THREAD

**Issue by WTRM3L0N** [Offline-Cheatbreaker/Client#15]
**Describe the bug**
 when i click to launch 1.8.9 it says launching but it never launches

**To Reproduce**

**Expected behavior**
 but it should of just launched 1.8.9

**Screenshots**

**Please complete the following information:**
 - OS: 
 - Game version: 
 - Game build number: 
 - Launcher version:  2.0.0 beta 8

**Additional context**
it sometimes will open for a split second then close

**Comment by ShonP40** [comment]
The issue was closed because the issue template was not filled out.
If the problem still occurs, create a new issue and fill out the template.
