### ISSUE TITLE
Launcher not downloading 1.8.9 version.

### ISSUE THREAD

**Issue by galaxyyb** [Offline-CheatBreaker/Client#18]
**Describe the bug**
When I try to download the 1.7.10 or 1.8.9 version of CheatBreaker Client, it gets stuck simillar to https://github.com/Offline-CheatBreaker/Client/issues/8.

**To Reproduce**
1. Go to Cheatbreaker Client
2. Click on Launch 1.7.10 or Launch 1.8.9
3. Scroll down to anywhere

**Screenshots**

![2021-07-26_11-09](https://user-images.githubusercontent.com/87984921/127003763-c0c94db7-c036-4c1f-a127-3813d2e6768f.png)

**Please complete the following information:**
 - OS: Linux (Lubuntu 20.04 - Ubuntu/Debian) 
 - Game version: 1.8.9 
 - Game build number: 
 - Launcher version: 2.0.0 Beta 9 
 - Java Version: 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
 

**Additional context**

Log file (I didn't find the log.log, only this renderer.log): 
[renderer.log](https://github.com/Offline-CheatBreaker/Client/files/6878868/renderer.log)

**Comment by ShonP40** [comment]
Looks like it got stuck when trying to create the game folder.

Can you try to run it as root and see if that helps?

**Comment by galaxyyb** [comment]
In case it would open with the sudo command?
Ex: sudo ./Offline\ CheatBreaker\ Beta

(and sorry if my English is bad, I don't speak so much this language)

**Comment by galaxyyb** [comment]
Because I've already tried this, and it gave an error with Chromium, which must be what the Client uses.

**Comment by galaxyyb** [comment]
```
lubuntu@lubuntu:/usr/bin/.offlinecheatbreaker$ sudo ./Offline\ CheatBreaker\ Beta
[19003:0726/125923.483846:FATAL:electron_main_delegate.cc(211)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap

```
![2021-07-26_12-59](https://user-images.githubusercontent.com/87984921/127021076-3fe06651-813c-45e4-b089-e491ab504602.png)

**Comment by ShonP40** [comment]
`sudo ./Offline\ CheatBreaker\ Beta --no-sandbox`

**Comment by galaxyyb** [comment]
apparently it's working, waiting here.
![2021-07-26_14-13](https://user-images.githubusercontent.com/87984921/127030905-455cfede-c0fe-4f5b-a441-8c8117bc214d.png)

**Comment by galaxyyb** [comment]
one more question, where is the "launcher accounts.json" file located?

**Comment by ShonP40** [comment]
In your Minecraft folder

**Comment by galaxyyb** [comment]
my pc froze because the browser is open but thanks! the client is working now

**Comment by ShonP40** [comment]
Alright, have a nice day
