### ISSUE TITLE
When I wanted to log in, we couldn't because I have a microsoft account and the migration has already started what I should do, thank you and have a nice rest

### ISSUE THREAD

**Issue by yKajotka** [Offline-CheatBreaker/Client#19]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: 
 - Game version: 
 - Game build number: 
 - Launcher version: 

**Additional context**

**Comment by yKajotka** [comment]
And you say that you will start support microsoft when migration start and it started

**Comment by yKajotka** [comment]
When I wanted to log in, we couldn't because I have a microsoft account and the migration has already started what I should do, thank you and have a nice rest

**Comment by ShonP40** [comment]
# Forwarded from our Discord server:

**Microsoft accounts support** will be worked on **after** Mojang starts the migration and sends one of our developers an invitation to migrate.

If you want to continue playing on Offline CheatBreaker, don't migrate to a Microsoft account until we add support for that system.

**Comment by yKajotka** [comment]
Thanks :D
