### ISSUE TITLE
Hypixel Level Head not view

### ISSUE THREAD

**Issue by lem0nb** [Offline-CheatBreaker/Client#21]
**Describe the bug**
Hypixel Level Head not view

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: Windows7
 - Game version: 1.8.9
 - Game build number: 
 - Launcher version: beta 10

**Additional context**

**Comment by lem0nb** [comment]
> Thanks for letting us know
> 
> A fix will be implemented in the next client update

and auto gg is broken too

**Comment by ShonP40** [comment]
Its working, just not on all Hypixel gamemodes

**Comment by ShonP40** [comment]
Also make sure that you're connecting through `*.hypixel.net` and not `hypixel.io`

**Comment by lem0nb** [comment]
> Also make sure that you're connecting through `*.hypixel.net` and not `hypixel.io`

I saw a blank black square on the user name during the war, and there was no level displayed
I'm using *.hypixel.net
auto gg work

**Comment by ShonP40** [comment]
> I saw a blank black square on the user name during the bedwar, and there was no level displayed

As stated before, it'll be fixed in the next client update

**Comment by lem0nb** [comment]
> > I saw a blank black square on the user name during the bedwar, and there was no level displayed
> 
> As stated before, it'll be fixed in the next client update

I update to 2.0.0 but auto gg and level headed is not working in bedwars game

**Comment by ShonP40** [comment]
I said in the next client update
not launcher update...

**Comment by lem0nb** [comment]
> I said in the next client update not launcher update...

oh sorry

**Comment by ShonP40** [comment]
Fixed with [v2022.2.1](https://github.com/Offline-CheatBreaker/Client/releases/tag/2022.2.1)
