### ISSUE TITLE
Friend List can't work on mc.hypixel.net

### ISSUE THREAD

**Issue by lem0nb** [Offline-CheatBreaker/Client#23]
### Describe the bug

Friend List can't work on mc.hypixel.net
it views nothing and I cannot add friend

### Steps To Reproduce

Go to Minecraft
Click on tab+shift

### Expected Behavior

idk

### Environment

```markdown
OS: Windows7
Game version: 1.8.9
Game build number: The newest
Launcher version: 2.0.0 release
```

**Comment by ShonP40** [comment]
Are you able to provide a screenshot?

**Comment by lem0nb** [comment]
> Are you able to provide a screenshot?

okay wait

**Comment by lem0nb** [comment]
> Are you able to provide a screenshot?

![image](https://user-images.githubusercontent.com/68461894/155824033-7f11e3b9-0616-43f3-af31-e85efaba6ab0.png)
