### ISSUE TITLE
AUTO WHO NOT WORK 

### ISSUE THREAD

**Issue by lem0nb** [Offline-CheatBreaker/Client#24]
### Describe the bug

Auto who not work in hypixel

### Steps To Reproduce

go to cheatbreaker 
go to hypixel
start auto who

### Expected Behavior

Auto who not work

### Environment

```markdown
OS: win7
Game version: 1.8.9
Game build number: Newest
Launcher version: 2.0.0
```

### Anything else?

No

**Comment by ShonP40** [comment]
Not an issue
`Auto Who` is only intended to work in ranked SkyWars games
![image](https://user-images.githubusercontent.com/13995143/158069012-acad6682-4de1-49e2-9c30-675c495a052d.png)

**Comment by lem0nb** [comment]
> 

i though it can use in bedwars because im using abyss-overlay

**Comment by lem0nb** [comment]
> Not an issue `Auto Who` is only intended to work in ranked SkyWars games ![image](https://user-images.githubusercontent.com/13995143/158069012-acad6682-4de1-49e2-9c30-675c495a052d.png)
i though it can use in bedwars because im using abyss-overlay

**Comment by ShonP40** [comment]
Abyss Overlay doesn’t require you to run `/who`

**Comment by ShonP40** [comment]
We may expand it in the future to work in other games

**Comment by lem0nb** [comment]
> 

OK thanks

**Comment by ShonP40** [comment]
P.S. The Forge version of this mod, and on other clients, also only works in ranked SkyWars

**Comment by ShonP40** [comment]
![image](https://user-images.githubusercontent.com/13995143/158160060-9051f1d9-d1d9-4a5e-ba5d-f7ac8127a306.jpeg)
