### ISSUE TITLE
After I updated,Stuck at loading

### ISSUE THREAD

**Issue by lem0nb** [Offline-CheatBreaker/Client#25]
### Describe the bug

After I updated,Stuck at loading,I waited about one hour
![Uploading 2022-3-20 19-4-9.png…]()

### Steps To Reproduce

Go to CheatBreaker
Update CheatBreaker
Go to Cheatbreaker
Click Lancher 1.8.9
Stuck at loding

### Expected Behavior

umm

### Environment

```markdown
OS: Windows7 X64
Game version: 1.8.9
Game build number: idk...
Launcher version: 2.1.0
```

**Comment by lem0nb** [comment]
![2022-3-20 19-4-9](https://user-images.githubusercontent.com/68461894/159159546-8d42ae72-7f5e-4cd2-b5c1-f94dd2279864.png)

**Comment by ShonP40** [comment]
Close the launcher

Go to `%appdata%`
Delete the `Offline CheatBreaker` folder

Open the launcher
And try to launch again

**Comment by lem0nb** [comment]
> Close the launcher
> 
> Go to `%appdata%` Delete the `Offline CheatBreaker` folder
> 
> Open the launcher And try to launch again

Stuck at downloading JDK
![image](https://user-images.githubusercontent.com/68461894/159160267-f882a5bc-a8df-47a5-9eb0-5e3c6b70d479.png)
need i open my vpn?

**Comment by ShonP40** [comment]
??

If it's taking a while, it just means that you have a slow connection

**Comment by lem0nb** [comment]
> ??
> 
> If it's taking a while, it just means that you have a slow connection

but i wait so long...

**Comment by lem0nb** [comment]
> Close the launcher
> 
> Go to `%appdata%` Delete the `Offline CheatBreaker` folder
> 
> Open the launcher And try to launch again

and is my config and logs still here

**Comment by ShonP40** [comment]
Launcher configs and logs are saved there

Game configs are saved in your Minecraft folder

**Comment by lem0nb** [comment]
> Launcher configs and logs are saved there
> 
> Game configs are saved in your Minecraft folder

still downloading jdk...:(

**Comment by lem0nb** [comment]
> > Launcher configs and logs are saved there
> > Game configs are saved in your Minecraft folder
> 
> still downloading jdk...:(
