### ISSUE TITLE
Choose custom java installation

### ISSUE THREAD

**Issue by Z1xus** [Offline-CheatBreaker/Client#26]
### Environment

Launcher

### Describe the suggestion

I would like to see in the client the ability to use a custom installation of java to run the game, with the ability to change it in the settings of the client.

### Anything else?

![Untitled-1](https://user-images.githubusercontent.com/40185941/164229027-6908c432-ea24-4f1d-a3a5-5b27fb36f11d.png)

**Comment by ShonP40** [comment]
1. You can already change the JRE by replacing the contents of `%appdata%\Offline CheatBreaker\jre`

2. Since this is an advanced option, that really shouldn’t be tempered with, I don’t think that it’ll ever make it into the UI

3. CB won’t start with Java 17
