### ISSUE TITLE
1.8.9

### ISSUE THREAD

**Issue by Keeboy99** [Offline-CheatBreaker/Client#27]
after the window that says cheatbreaker 1.8.9 it crashes.

Need help fixing

**Comment by ShonP40** [comment]
Can you send the `renderer.log` file using the `SHOW LOGS` button in the launcher’s `ABOUT` section to our email (contact@offlinecheatbreaker.com)?

**Comment by Keeboy99** [comment]
[renderer.log](https://github.com/Offline-CheatBreaker/Client/files/8568700/renderer.log)
here IDK if I uploaded right

**Comment by ShonP40** [comment]
The shaders you’re using (`Sildur's+Vibrant+Shaders+v1.32+Lite`) are not supported on Offline CheatBreaker.

Offline CheatBreaker only supports 1.7-1.8.9 shaders, any shaders that support newer versions as well will crash the game due to invalid textures.

Disable your shaders and launch CB again

**Comment by Keeboy99** [comment]
welp all I can say is I am so dumb I only had those on becuse I was using lunar xd

**Comment by ShonP40** [comment]
Alright
Also, use the `Bug report` issue template next time
