### ISSUE TITLE
Offline cheatbreaker not launching

### ISSUE THREAD

**Issue by NewAmazingPVP** [Offline-CheatBreaker/Client#28]
### Describe the bug

Offline cheatbreaker doesn't launch at all. (This is my first time using it too btw) I have uninstalled and reinstalled multiple times. I disabled anti-virus and even gave the app admin rights, But still both versions i.e. 1.7.10 or 1.8.9 still don't launch from the launcher for some reason. I have checked and made sure that I have at least 300MB available on my main system drive. My network connection is configured as a Home/Private network and not a Public network
My firewall isn't blocking the Offline CheatBreaker launcher because disabling it still doesn't launch it
I have a stable internet connection
My system time and date are configured correctly
Any help would be appreciated :)

### Steps To Reproduce

Download latest version from website install it and try to launch either 1.7.10 or 1.8.9 and it won't launch

### Expected Behavior

1.7.10 and 1.8.9 versions should launch but it doesn't

### Environment

```markdown
OS: Windows 10
Game version: both 1.7.10 and 1.8.9
Game build number: 3.3.0 (1.7.10) & 3.1.7 (1.8.9)
Launcher version: 2.1.1
```

### Anything else?

Thanks for help in advance

**Comment by ShonP40** [comment]
When you click on the launch button, does it start the launching process or just doesn't respond to the click?

**Comment by NewAmazingPVP** [comment]
Oh thank you for your fast response! So yeah basically it just doesn't repond to the click at all whatsoever. And my bad the launcher version is 2.1.1

**Comment by ShonP40** [comment]
Can you try a different internet connection? (Like a mobile hotspot)

**Comment by NewAmazingPVP** [comment]
Sadly I have no other networks available and I can't use mobile hotspot because my phone plan doesn't allow hotspots. Im sry for that

**Comment by ShonP40** [comment]
The issue you described, currently only occurred to about 10 other people.

We're currently working on a launcher update that'll enable more debugging so we could figure out what's causing the issue you're experiencing.

Once we release it, download it and see if your issue has been fixed, if it was, you can close this issue.

**Comment by NewAmazingPVP** [comment]
Alright thank you for your help if the issue does get fixed in the future release I will definitely close this

**Comment by ShonP40** [comment]
Are you able to download & try the newest launcher?

**Comment by NewAmazingPVP** [comment]
Oops sorry for not keeping up to date but I just downloaded the latest version (2.1.5) of the launcher and tried to launch but it still doesnt launch. But unlike previously it does give an error 
![image](https://user-images.githubusercontent.com/87737759/171017545-2c9bef94-9659-4609-992c-3ac4d6582b1e.png) I think theres something wrong with my internet or something I am not sure.

**Comment by ShonP40** [comment]
Can you click on the `About` button (at the top right corner), click on `Show logs`
And send the `renderer` file to our support email (`support@offlinecheatbreaker.com`)?

**Comment by NewAmazingPVP** [comment]
Alright I sent the renderer.log file to that email address

**Comment by ShonP40** [comment]
Are you able to access `https://api.offlinecheatbreaker.com/profile/4967f622174a4d2ead421ed4f2b1804f` through a web browser?

**Comment by ShonP40** [comment]
Because it looks like the launcher can't access it (from the log you sent)

**Comment by NewAmazingPVP** [comment]
When I go to the website it says this 
![image](https://user-images.githubusercontent.com/87737759/171032820-6e1b9801-dfcf-4f20-936e-8bfe287535a7.png)

**Comment by ShonP40** [comment]
so your web browser can access it

Do you have any firewalls/antivirus's installed that aren't from Microsoft?

**Comment by NewAmazingPVP** [comment]
Yes I do have kaspersky antivirus

**Comment by ShonP40** [comment]
Can you try to disable its **firewall** temporarily to see if that changes anything?

**Comment by NewAmazingPVP** [comment]
Should I disable it to see if it works?

**Comment by NewAmazingPVP** [comment]
Ok alright let me try

**Comment by NewAmazingPVP** [comment]
I disabled the file antivirus but still doesn't work 
![image](https://user-images.githubusercontent.com/87737759/171033302-34bc3f0d-fb7f-4ff8-839e-3411990c4866.png)

**Comment by ShonP40** [comment]
Its not file antivirus
You need to find the firewall section (or web antivirus)

**Comment by ShonP40** [comment]
Its could be a part of the safe browsing feature (never used that antivirus)

**Comment by NewAmazingPVP** [comment]
Ok alright let me disable that one

**Comment by NewAmazingPVP** [comment]
i disabled everything sitll same issue 
![image](https://user-images.githubusercontent.com/87737759/171033573-37f975c0-c170-4eab-ad1b-a055e4648513.png)
Also I forgot to tell i have both windows defender and this antivurs enabled so I disable them both?

**Comment by ShonP40** [comment]
Microsoft-made anti malware protection doesn't cause issues
Only some third party ones do sometimes

**Comment by ShonP40** [comment]
Can you try the steps here do disable the firewall in kaspersky?
https://support.kaspersky.com/KSVLA/5.0/en-US/145822.htm

**Comment by NewAmazingPVP** [comment]
Alright let me try though I don't think kaspersky free version has firewall its only the paid versions if I am right. But let me still try it

**Comment by NewAmazingPVP** [comment]
Sadly I can't find any of those options in my free version. After googling I found out that the free version indeed doesnt have a firewall and onloy paid ones have it 
![image](https://user-images.githubusercontent.com/87737759/171034321-976e8c35-7138-445c-966d-7b2b7a518d0f.png)

**Comment by ShonP40** [comment]
Are you sure that your Windows network settings are set to `Private` and not `Public`?
(You can check if in the Windows control center)

**Comment by NewAmazingPVP** [comment]
![image](https://user-images.githubusercontent.com/87737759/171034637-34b893d0-23d8-4dd2-bb87-3363a693057f.png)
Its private

**Comment by ShonP40** [comment]
Do you have a VPN enabled?

**Comment by NewAmazingPVP** [comment]
No i dont have a vpn. But sometimes when I just boot up normal mc a pop up from windows firewall appears saying it has blocked some features of this app. 
![image](https://user-images.githubusercontent.com/87737759/171034860-05c3a86e-4d74-45fa-991e-c81766145aad.png)
Is it the same issue with this?

**Comment by NewAmazingPVP** [comment]
Windows firewall probably blocks cheatbreaker to communicate i think?

**Comment by ShonP40** [comment]
That pop up is normal for most apps that require internet access (especially Java ones like MC)

Doesn't happen with Electron apps though (like our launcher)

**Comment by ShonP40** [comment]
Are you able to connect your PC to your router with an Ethernet cable (instead of WiFi) and check if that changes anything?

**Comment by NewAmazingPVP** [comment]
Sadly I cannot connect with Ethernet cable because my PC is in basement whereas the router is upstairs

**Comment by NewAmazingPVP** [comment]
Should i uninstall kaspersky for a bit to see if that works?

**Comment by ShonP40** [comment]
Sure.
Restart your PC after doing that though

**Comment by NewAmazingPVP** [comment]
alright brb in a bit then

**Comment by NewAmazingPVP** [comment]
I uninstalled kaspersky restarted and even uninstalled and reinstalled cheatbreaker sitll same issue. I think its something else which is preventing

**Comment by NewAmazingPVP** [comment]
Log files says this error [2022-05-30 13:09:15.828] [error] [Services authentication] There was an error trying to authenticate the launcher: FetchError: invalid json response body at https://api.offlinecheatbreaker.com/profile/4967f622174a4d2ead421ed4f2b1804f reason: Unexpected token < in JSON at position 0
[2022-05-30 13:09:18.266] [error] [Services authentication] There was an error trying to authenticate the launcher: FetchError: invalid json response body at https://api.offlinecheatbreaker.com/profile/4967f622174a4d2ead421ed4f2b1804f reason: Unexpected token < in JSON at position 0
[2022-05-30 13:09:23.669] [error] [Services authentication] There was an error trying to authenticate the launcher: FetchError: invalid json response body at https://api.offlinecheatbreaker.com/profile/4967f622174a4d2ead421ed4f2b1804f reason: Unexpected token < in JSON at position 0

**Comment by ShonP40** [comment]
ok, so, I just checked our CloudFlare and turns out that for whatever reason, it started blocking some launchers
I'll try to prevent it from doing so and report back

**Comment by ShonP40** [comment]
alright, I think that I got it.

Can you restart the Offline CheatBreaker launcher and try to launch again?

**Comment by NewAmazingPVP** [comment]
OMG IT WORKED! Tysm your time and help I really appreciate it. Not so many devs are helpful like u were. 
![image](https://user-images.githubusercontent.com/87737759/171036895-f157f9d9-9aa9-4140-9fa5-a3fea59f3020.png)

**Comment by NewAmazingPVP** [comment]
Both versions work now so thanks again Ill close this issue now

**Comment by ShonP40** [comment]
np, Have a nice day

**Comment by NewAmazingPVP** [comment]
you, too, man
