### ISSUE TITLE
1.7.10 not opening/crashing on launch

### ISSUE THREAD

**Issue by bonkay** [Offline-CheatBreaker/Client#29]
### Describe the bug

whenever I open cheatbreaker on 1.7 i get an error msg (CB-92e5f6e7-eee6-4c2d-9b93-19cdd90498df) 

### Steps To Reproduce

open cheatbreaker on 1.7.10

### Expected Behavior

Cheatbreaker should open properly when i launch 1.7.10

### Environment

```markdown
OS: 
Game version: 
Game build number: 
Launcher version:
```

**Comment by ShonP40** [comment]
The issue was closed because the issue template was not filled out.
If the problem persists, create a new issue and fill out the template completely (this includes the Environment section).
