### ISSUE TITLE
Can't play it offline

### ISSUE THREAD

**Issue by tkit0428** [Offline-CheatBreaker/Client#33]
### Describe the bug

There was an error trying to launch the client

Make sure that you have an active internet connection and try again later

### Steps To Reproduce

I disconnected the internet

Clicked launch

Waited for a few sec

Error popped up

### Expected Behavior

I expected to be able to play offline

### Environment

```markdown
OS: macOS 12.5 beta
Game version: 1.8.9
Game build number: Not sure
Launcher version: 2.1.5
```

**Comment by ShonP40** [comment]
As stated in the error message, you need to have an active internet connection to launch the game.


`Offline` in Offline CheatBreaker's name stands for the fact that it doesn't require the original CheatBreaker servers to run, not that it can run without an internet connection at all.
