### ISSUE TITLE
Hello, i have a one problem.

### ISSUE THREAD

**Issue by DrBananaboat** [Offline-CheatBreaker/Client#35]
### Describe the bug

Previously, I did not have such problems, Java is installed, everything is ready, but for some reason I have it on Mac Os 10.10. 5 YOSEMITE it won't start and this is an error, how can I fix it? Thanks in advance.
![Снимок экрана 2022-08-30 в 16 55 43](https://user-images.githubusercontent.com/112480971/187419801-89771f64-ebfb-4606-9538-d1073915cadb.png)
advance.

### Steps To Reproduce

![Снимок экрана 2022-08-30 в 16 55 43](https://user-images.githubusercontent.com/112480971/187420723-7dd3d901-8906-49c6-b049-d2aee5850380.png)
Look at errorat mid.

### Expected Behavior

I did not expect this, before it started, even rebootedю

### Environment

```markdown
OS: 10.10.5
Game version:1.8.9
Game build number: I dont know, sorry.
Launcher version: 2.1.5
```

**Comment by DrBananaboat** [comment]
Wait if u cant translate, where is it: Failed to open program "Offline Cheatbreaker" due to corruption. Moved the program to the trash.

**Comment by ShonP40** [comment]
As stated on the downloads page, macOS El Capitan (10.11) is the lowest supported version.

Anything below it will not work due to changes in Electron 11 (the framework our launcher uses).

**Comment by ShonP40** [comment]
You can probably upgrade to macOS High Sierra (10.13) or Mojave (10.14) with no issues

(Send the specs of your Mac so I could check what its latest supported version)

**Comment by DrBananaboat** [comment]
> Вероятно, вы можете без проблем перейти на macOS High Sierra (10.13) или Mojave (10.14).
> 
> (Отправьте характеристики вашего Mac, чтобы я мог проверить, какая его последняя поддерживаемая версия)

OS X YOSEMITE
Mac 10.10,.5
Mac pro (Mid 2010)

**Comment by ShonP40** [comment]
And what GPU do you have?
(You can check it in the `About this Mac` menu)

**Comment by ShonP40** [comment]
If you have a `Metal` compatible GPU, you can update to macOS Mojave (10.14), otherwise High Sierra (10.13) is the latest you can update to

**Comment by DrBananaboat** [comment]
I can download a old CB version? And no, i havent Metal.

> Если у вас есть `Metal`совместимый графический процессор, вы можете обновить его до macOS Mojave (10.14), в противном случае High Sierra (10.13) — это последняя версия, до которой вы можете обновить

**Comment by DrBananaboat** [comment]
How i'm understand it's that impossible.

**Comment by ShonP40** [comment]
> I can download a old CB version?
No, older versions that did support Yosemite have been disconnected ages ago.

> i havent Metal.
You can't know that while running such an old version of macOS.
Just check the model of your GPU (graphics card) in the `About This Mac` menu
