### ISSUE TITLE
Drop stack does not work standalone

### ISSUE THREAD

**Issue by Luk4x** [Offline-CheatBreaker/Client#39]
### Describe the bug

i cannot find the drop stack option in cheatbreaker menu like the other version, and the drop stack option in minecraft controls is not working.

### Steps To Reproduce

search for the drop stack option in cheatbreaker option and you'll not find, and try change the drop stack option in minecraft controls to 'Q' and it will not work, and the drop behavior will not work too.

### Expected Behavior

like the other versions, i expected that once a configured the drop stack option, even in cheatbreaker options or in minecraft options, to 'Q', it will work and drop all items in the stack with only pressing 'Q'.

### Environment

```markdown
OS: Linux Pop!_OS 22.04
Game version: 1.8.9
Game build number: 1f0f98b
Launcher version: 2.2.5
```

**Comment by Tellinq** [comment]
When setting drop stack, you are actually meant to use that key as an **additional** key to press, not that alone. If you bind it to Q, and if your initial drop stack Keybind is Q, that will not work.

This will be marked as potentially bad behavior and will consider changing it.

**Comment by Tellinq** [comment]
An update on this issue:

In my development environment, I have moved Drop Stack and Emote Wheel Buttons directly into CheatBreaker Settings front and center. For most who are first unaware, they can utilize the search bar to find what they are looking for

![image](https://cdn.discordapp.com/attachments/933498259379482705/1069750635592945734/image.png)

This will fix the issue where drop stack will not properly work and should stop interfering with bother keybinds. This should also fix an issue where if you set the drop stack key and drop item key as the same thing, it wouldn't work. Now, it will act as dropping the entire stack by default

I could also make this an option where you can choose to make drop stack work when only pressing that key or act as a modifier where you must press both Drop Item and Drop Stack keybinds to trigger drop stack. Let me know if this sounds appealing or not.

**Comment by Luk4x** [comment]
I see... In this case I searched a lot and also used the search, but it does not show results when searching for the drop stack:
![Screenshot from 2023-01-31 15-39-01](https://user-images.githubusercontent.com/86276393/215854129-a01fea7e-6a95-4bcb-938e-052f30aeae78.png)
Also, there is no 'Keybind Settings' option, the closest thing there is to 'Keybind handling Settings'.

But 'make this an option where you can choose to make the drop stack work just by pressing that key' sounds really appealing to me.

**Comment by ShonP40** [comment]
As @Tellinq mentioned before, these options are still in development.
Only our beta testers have access to them at the moment.

**Comment by Luk4x** [comment]
@ShonP40 oh, my bad bro, I got it now 😂

**Comment by ShonP40** [comment]
@Luk4x We pushed this to prod earlier today, check if it fixes your issue

**Comment by Luk4x** [comment]
@ShonP40 Yes, it's fixed! Thank you very much!
