### ISSUE TITLE
There is a problem in the game after startup

### ISSUE THREAD

**Issue by NotSis** [Offline-CheatBreaker/Client#40]
### Describe the bug

My inventory is always in the lower right corner, and the game keeps reporting errors！
[renderer.old.log](https://github.com/Offline-CheatBreaker/Client/files/10742290/renderer.old.log)

### Steps To Reproduce

aaaaa

### Expected Behavior

aaaaa

### Environment

```markdown
OS: MacOS 10.14
Game version: 1.8.9
Game build number: 02b35e
Launcher version: 2.2.5
```

### Anything else?

[renderer.old.log](https://github.com/Offline-CheatBreaker/Client/files/10742320/renderer.old.log)

**Comment by ShonP40** [comment]
Go to the `Advanced` section in the launcher and press on the `Reset game downloads` button

**Comment by ShonP40** [comment]
Also, never send logs in public chats without making sure that they don’t include any personal info you care about & fill out the template properly

**Comment by NotSis** [comment]
thanks

**Comment by NotSis** [comment]
？？Why didn't it work？？

**Comment by ShonP40** [comment]
You mean that it still doesn’t work, or are you asking why it didn’t work in the beginning?

**Comment by ShonP40** [comment]
If you’re still experiencing the issues you described, please create a new GitHub issue and fill out the template properly.

Closing this one due to a missing template.

**Comment by NotSis** [comment]
It's still useless.

**Comment by ShonP40** [comment]
> If you’re still experiencing the issues you described, **please create a new GitHub issue and fill out the template properly**.
> 
> Closing this one due to a missing template.
