### ISSUE TITLE
 game always crashes

### ISSUE THREAD

**Issue by NotSis** [Offline-CheatBreaker/Client#41]
### Describe the bug

The game will collapse as soon as you open the mod menu.

### Steps To Reproduce

ee

### Expected Behavior

ee

### Environment

```markdown
OS: MacOS
Game version: 1.7.10
Game build number: dbacb5a/master
Launcher version: 2.2.5
```

### Anything else?

[renderer.log](https://github.com/Offline-CheatBreaker/Client/files/10775574/renderer.log)
[renderer.log](https://github.com/Offline-CheatBreaker/Client/files/10775575/renderer.log)

**Comment by Tellinq** [comment]
This is an incomplete report. You __**must**__ fill out the template properly. Putting placeholder characters will not be accepted. Where are the steps to reproduce the issue? Where are videos of this happening? Just because this issue occurs to you, does not mean it is actually happening to everyone.

I for one cannot replicate this issue. Until you edit this post with the proper requirements, there will not be any support. No exceptions.

**Comment by Tellinq** [comment]
![image](https://user-images.githubusercontent.com/59412384/219909943-927ba110-6aa6-4d32-b7aa-55e14bf91071.png)
As further notice, here is a screenshot proving that this does not happen to me. 

For now, I will just recommend this:

1. In your Minecraft directory go to the `config` folder and __**delete**__ `cheatbreaker-client-1.7.10-master`.

If you are unsure where to locate your Minecraft directory, the default location on **macOS** is `~/Library/Application Support/minecraft`. You can also confirm this by going to the `SETTINGS` tab on our launcher and finding the text after `Game Directory`.

2. Click the __**ADVANCED**__ tab
![image](https://user-images.githubusercontent.com/59412384/219910054-5d9f172b-30ae-4a8e-b840-fb9b4c6222db.png)

3. Click __**Reset All**__
![image](https://user-images.githubusercontent.com/59412384/219910123-8240dfc8-90d2-4e50-b915-133ed0e2a980.png)

4. You will get a prompt to restart the launcher. Proceed with the prompt. Once the launcher reloads, relaunch `1.7.10`.

**Comment by ShonP40** [comment]
And as stated earlier, don’t upload launcher logs in public chats without removing personal information from them.
Deleted your logs.

**If you create another issue without filling out the template properly, we’ll have to block your account from opening any further issues.**
