### ISSUE TITLE
Official MC Launcher problem

### ISSUE THREAD

**Issue by ILOVECHEATING** [Offline-Cheatbreaker/Client#9]
So i just wanna use the mc launcher to launch the game because i use multiple versions of minecraft,  so I took the Offline CB 1.8 in the following address: C:\Users\...\AppData\Roaming\Offline CheatBreaker\game\1.8.9\versions\OfflineCheatBreaker 1.8.9
I downloaded an run the game once via Beta 8 Launcher
The Official MC launcher throw me an error:
Failed to download file. 
Name: Offline CheatBreaker 1.8.9.jar
Url: https://s3.amazonaws.com/Minecraft.Download/versions/Offline CheatBreaker1.8.9/Offline cheatbreaker 1.8.9.jar
Filename on disk: Offline CheatBreaker 1.8.9.jar
Path: C:\Users\...\AppData\Roaming\.minecraft\versions\Offline CheatBreaker 1.8.9\Offline CheatBreaker 1.8.9.jar
Exists: File
Plz help, using many launchers for one game is so annoying ngl :(

**Comment by ShonP40** [comment]
We don't support launching through the normal MC launcher.

If you want to play on Offline CB, you'll have to use our launcher. You can download it from our website: https://offlinecheatbreaker.com
